src/Entity/Lentillas.php
<?php

namespace App\Entity;

use App\Repository\LentillasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: LentillasRepository::class)]
#[Vich\Uploadable]
class Lentillas
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $marca = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $descripcion = null;

    #[ORM\Column(length: 255)]
    private ?string $tipo_producto = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $frecuencia = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tipo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $material = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 6, scale: 2)]
    private ?string $precio = null;

    #[ORM\Column]
    private ?int $iva = null;

    #[ORM\Column(nullable: true)]
    private ?int $descuento = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column]
    private ?bool $destacado = null;

   

    //imagen1
    #[Vich\UploadableField(mapping: 'lentillas', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    private ?int $categoria = null;

    #[ORM\Column]
    private ?bool $estado = null;
    
    
    //METODOS....



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarca(): ?string
    {
        return $this->marca;
    }

    public function setMarca(string $marca): static
    {
        $this->marca = $marca;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getTipoProducto(): ?string
    {
        return $this->tipo_producto;
    }

    public function setTipoProducto(string $tipo_producto): static
    {
        $this->tipo_producto = $tipo_producto;

        return $this;
    }

    public function getFrecuencia(): ?string
    {
        return $this->frecuencia;
    }

    public function setFrecuencia(?string $frecuencia): static
    {
        $this->frecuencia = $frecuencia;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(?string $tipo): static
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getMaterial(): ?string
    {
        return $this->material;
    }

    public function setMaterial(?string $material): static
    {
        $this->material = $material;

        return $this;
    }

    public function getPrecio(): ?string
    {
        return $this->precio;
    }

    public function setPrecio(string $precio): static
    {
        $this->precio = $precio;

        return $this;
    }

    public function getIva(): ?int
    {
        return $this->iva;
    }

    public function setIva(int $iva): static
    {
        $this->iva = $iva;

        return $this;
    }

    public function getDescuento(): ?int
    {
        return $this->descuento;
    }

    public function setDescuento(?int $descuento): static
    {
        $this->descuento = $descuento;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getDestacado(): ?bool
    {
        return $this->destacado;
    }

    public function setDestacado(?bool $destacado): static
    {
        $this->destacado = $destacado;

        return $this;
    }



     //añadir imagenes
    //imagen1
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getCategoria(): ?int
    {
        return $this->categoria;
    }

    public function setCategoria(int $categoria): static
    {
        $this->categoria = $categoria;

        return $this;
    }

    public function isEstado(): ?bool
    {
        return $this->estado;
    }

    public function setEstado(bool $estado): static
    {
        $this->estado = $estado;

        return $this;
    }
}

templates/correos/clienteCompra.html.twig
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmación de Pedido</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f7fc;
            margin: 0;
            padding: 0;
            color: #333;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #555555;
        }
        h3 {
            color: #444444;
        }
        p {
            font-size: 16px;
            line-height: 1.6;
            color: #555;
        }
        .btn {
            display: inline-block;
            background-color: #9736af;
            color: white;
            padding: 12px 25px;
            text-decoration: none;
            border-radius: 5px;
            text-align: center;
            font-weight: bold;
            margin-top: 10px;
            width: auto;
        }
        .btn:hover {
            background-color: #712282;
        }
        .expired {
            font-size: 12px;
            color: #aaa;
            margin-top: 10px;
        }
        .footer {
            margin-top: 30px;
            font-size: 14px;
            text-align: center;
            color: #888;
        }
        .order-summary {
            margin-top: 20px;
        }
        .order-summary ul {
            list-style: none;
            padding: 0;
        }
        .order-summary li {
            margin-bottom: 10px;
            display: flex;
            justify-content: space-between;
        }
        .order-summary .total {
            font-weight: bold;
            font-size: 16px;
            color: #333;
        }
        .order-summary .shipping {
            color: #555;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>¡Gracias por tu pedido!</h1>

        <p>Hemos recibido tu pedido y estamos procesándolo. A continuación te mostramos un resumen de tu compra:</p>

        <div class="order-summary">
            <h3>Resumen de pago</h3>
            <ul>
                {% set total = 0 %}
                {% for producto in carrito %}
                    <li>
                        {% if producto['producto'].categoria == 1 %}
                            Marca: {{producto['producto'].marca}}, Modelo: {{producto['producto'].modelo}}, Tipo: {{producto['producto'].tipo}}, (x{{ producto['cantidad'] }}, {{ producto['producto'].precio }}€)
                        {% endif %}
                        
                        {% if producto['producto'].categoria == 2 %}
                            Marca: {{producto['producto'].marca}}, Tipo: {{producto['producto'].tipoProducto}}, (x{{ producto['cantidad'] }}, {{ producto['producto'].precio }}€)
                        {% endif %}
                        
                        {% set total = total + (producto['producto'].precio * producto['cantidad']) %}
                    </li>
                {% else %}
                    <li>Productos <span>€0</span></li>
                {% endfor %}
                <li class="shipping">
                    Envío: Gratis
                </li>
                <li class="total">
                    <div>
                        <strong>Total (incluye IVA): {{ total }}€</strong>
                    </div>
                </li>
            </ul>
        </div>

        <p class="footer">¡Gracias por elegirnos!</p>
    </div>
</body>
</html>

templates/correos/pagoIncorrecto.html.twig
<div>
      <h3>Debemos informale que el pago realizado es inferior al procesado en nuestra base de datos</h3>
      <p>Nuestro servcio de atención al cliente se pondrá en contacto con usted lo antes posible. Si lo desea puede contactar con nosotros en horario de --</p>

      <p>Resumen  de Compra:</p>
      <ul >
      {% set total = 0 %}
      {% for producto in carrito %}
        <li>
          {% if producto['producto'].categoria==1 %}
                Marca: {{producto['producto'].marca}} , Modelo: {{producto['producto'].modelo}}, Tipo: {{producto['producto'].tipo}}, (x{{ producto['cantidad']  }})
                <span>€{{ (producto['producto'].precio * producto['cantidad']) }}</span>
          {% endif %}
          {% if producto['producto'].categoria==2 %}
                Marca: {{producto['producto'].marca}} , Tipo: {{producto['producto'].tipoProducto}}, (x{{ producto['cantidad']  }})
          {% endif %}  
               <span>€{{ (producto['producto'].precio * producto['cantidad']) }}</span>
          {% set total = total + (producto['producto'].precio * producto['cantidad']) %}
        </li>
        <li>Pago Realizado: {{cantidadPagada}}.
       </ul>
        {% endfor %}

templates/correos/procesoIncompleto.html.twig
 <div>
      <h3>Debemos informale que hay algún problema en el pago realizado</h3>
      <p>Nuestro servcio de atención al cliente se pondrá en contacto con usted lo antes posible. Si lo desea puede contactar con nosotros en horario de --</p>

      <p>Resumen  de Compra:</p>
      <ul >
      {% set total = 0 %}
      {% for producto in carrito %}
        <li>
          {% if producto['producto'].categoria==1 %}
                Marca: {{producto['producto'].marca}} , Modelo: {{producto['producto'].modelo}}, Tipo: {{producto['producto'].tipo}}, (x{{ producto['cantidad']  }})
                <span>€{{ (producto['producto'].precio * producto['cantidad']) }}</span>
          {% endif %}
          {% if producto['producto'].categoria==2 %}
                Marca: {{producto['producto'].marca}} , Tipo: {{producto['producto'].tipoProducto}}, (x{{ producto['cantidad']  }})
          {% endif %}  
               <span>€{{ (producto['producto'].precio * producto['cantidad']) }}</span>
          {% set total = total + (producto['producto'].precio * producto['cantidad']) %}
        </li>
       </ul>
        {% endfor %}